# Generated by Django 4.1.3 on 2023-04-19 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
