# Generated by Django 4.1.3 on 2023-04-19 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
