# Generated by Django 4.1.3 on 2023-04-20 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_tag_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product_color', models.CharField(max_length=24)),
                ('product_detail', models.TextField()),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.category')),
                ('product_discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.discount')),
                ('product_tag', models.ManyToManyField(to='core.tag')),
            ],
        ),
    ]
